const toggle=document.querySelector('.mobile-toggle'), menu=document.getElementById('mobileMenu');toggle.addEventListener('click',()=>{menu.hidden=!menu.hidden;toggle.setAttribute('aria-expanded',String(!menu.hidden));toggle.setAttribute('aria-label',menu.hidden?'Open menu':'Close menu')});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!menu.hidden){menu.hidden=true;toggle.setAttribute('aria-expanded','false');toggle.focus()}});document.querySelectorAll('.nav-link').forEach(a=>{if(a.getAttribute('href')===location.pathname.split('/').pop())a.setAttribute('aria-current','page')});document.querySelectorAll('form[data-draft]').forEach(form=>{const key='km-draft-'+form.dataset.draft,status=form.querySelector('.form-status');try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved){for(const [name,value] of Object.entries(saved)){const field=form.elements.namedItem(name);if(field)field.value=value}status.textContent='Your saved draft has been restored.'}}catch{}form.addEventListener('submit',e=>{e.preventDefault();try{localStorage.setItem(key,JSON.stringify(Object.fromEntries(new FormData(form))));status.textContent='Draft saved on this device. No message has been sent.'}catch{status.textContent='Your browser could not save the draft. Keep this page open to retain your entries.'}});form.querySelector('.clear-draft').addEventListener('click',()=>{try{localStorage.removeItem(key)}catch{}form.reset();status.textContent='Draft cleared.'})});document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelectorAll('.resource-item').forEach(card=>card.hidden=button.dataset.filter!=='all'&&card.dataset.kind!==button.dataset.filter)}));function revealHash(){const target=document.getElementById(location.hash.slice(1));if(target?.classList.contains('resource-item')&&target.hidden)document.querySelector('[data-filter="all"]').click()}window.addEventListener('hashchange',revealHash);revealHash();
const carousel=document.querySelector('.events-slideshow');
if(carousel){
 const slides=[...carousel.querySelectorAll('.events-slide')],dots=[...carousel.querySelectorAll('[data-slide]')],pause=carousel.querySelector('.slide-pause'),status=carousel.querySelector('.slide-status');
 const motion=window.matchMedia('(prefers-reduced-motion: reduce)');
 let current=0,playing=!motion.matches,timer;
 function show(index,announce=false){current=(index+slides.length)%slides.length;slides.forEach((slide,i)=>{slide.hidden=i!==current;slide.classList.toggle('is-active',i===current)});dots.forEach((dot,i)=>dot.setAttribute('aria-pressed',String(i===current)));if(announce)status.textContent=`Image ${current+1} of ${slides.length}`;else{status.setAttribute('aria-live','off');status.textContent=`Image ${current+1} of ${slides.length}`;status.setAttribute('aria-live','polite')}}
 function schedule(){clearInterval(timer);pause.textContent=playing?'Pause slideshow':'Play slideshow';if(playing&&!document.hidden&&!carousel.matches(':hover')&&!carousel.contains(document.activeElement))timer=setInterval(()=>show(current+1),6500)}
 carousel.querySelector('.slide-prev').addEventListener('click',()=>{show(current-1,true);schedule()});
 carousel.querySelector('.slide-next').addEventListener('click',()=>{show(current+1,true);schedule()});
 dots.forEach(dot=>dot.addEventListener('click',()=>{show(Number(dot.dataset.slide),true);schedule()}));
 pause.addEventListener('click',()=>{playing=!playing;schedule()});
 carousel.addEventListener('mouseenter',()=>clearInterval(timer));carousel.addEventListener('mouseleave',schedule);
 carousel.addEventListener('focusin',()=>clearInterval(timer));carousel.addEventListener('focusout',()=>setTimeout(schedule,0));
 carousel.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();show(current+(event.key==='ArrowLeft'?-1:1),true);schedule()}});
 document.addEventListener('visibilitychange',schedule);motion.addEventListener('change',()=>{if(motion.matches)playing=false;schedule()});schedule();
}
